.TH mkfsqueue 1 "2012-06-12" "AxialMarket" "AxialMarket System Commands Manual"
.SH NAME
mkfsqueue - make
.BR fsq (7)
queues in the file-system
.SH SYNOPSIS
.B mkfsqueue
[
.I flags
]
.I path/to/queue
.br
.B mkfsqueue
[
.B \-vVpDF
] [
.B \-q
.I queue_name
] [
.B \-d
.I done_name
] [
.B \-f
.I fail_name
] [
.B \-t
.I tmp_name
] [
.B \-P
.I fifo_name
] [
.B \-n
.I down_name
] [
.B \-o
.I owner
] [
.B \-g
.I group
] [
.B \-m
.I mode
] [
.I path
[
.IR path ...
]
.SH DESCRIPTION
The
.B mkfsqueue
program installs an
.BR fsq (7)
compliant queue to one or more
.BR path s.
An
.BR fsq (7)
compliant queue uses files as representations of work, and uses directories to
track the state of that work.  The
.B mkfsqueue
program provides a simple interface to setup the directories used to track work
as subdirectories of
.B path .
.SH OPTIONS
.TP
.B \-h
Help.  Print usage to stdout and exit 0.
.TP
.B \-v
Verbose.  Print additional diagnostic information to stderr.
.TP
.B -V
No Verbose.  Do not print diagnostic information to stderr. (Default)
.TP
.B -p
Pipe.  Install a
.BR fifo (7)
to
.IR path .
The
.B \-p
option is provided to setup an
.BR fsq (7)
queue to be scanned by the
.BR trigger\-listen (1)
program.
.TP
.B \-D
Down.  Install the
.BR fsq (7)
compliant queue in down state.
.BR fsq (7)
compliant queue scanning utilities will not process work in this state.
.TP
.B \-F
Force.  Recursively unlink target
.IR path s
prior to installing queue directories.  Use of the
.B \-F
option causes each
.I path
installed to be non-idempotent.
.TP
.BI \-q queue_name
Install queue directory with the name
.I queue_name
to
.IR path s.
.I queue_name
may not be empty, may not be named `.' or `..', and may not contain `/'s.
(Default: queue)
.TP
.BI \-d done_name
Install done directory with the name
.I done_name
to
.IR path s.
.I done_name
may not be empty, may not be named `.' or `..', and may not contain `/'s.
(Default: done)
.TP
.BI \-f fail_name
Install fail directory with the name
.I fail_name
to
.IR path s.
.I fail_name
may not be empty, may not be named `.' or `..', and may not contain `/'s.
(Default: fail)
.TP
.BI \-t tmp_name
Install tmp directory with the name
.I tmp_name
to
.IR path s.
.I tmp_name
may not be empty, may not be named `.' or `..', and may not contain `/'s.
(Default: tmp)
.TP
.BI \-P fifo_name
Install optional
.BR fifo (7)
to
.IR path s
with name
.IR fifo_name .
.B \-n
will set the
.B \-p
option.  (Default: trigger-s)
.TP
.BI \-n down_name
Install down file with name
.I down_name
to
.I path s.
.B \-n
will set the
.B \-D
option.  (Default: down)
.TP
.BI \-o owner
Install all directories, fifos and files with the owner
.IR owner ,
instead of the effective user ID of the calling process.  Either a user login
name or a numeric user ID are accepted.
.TP
.BI \-g group
Install all directories, fifos and files with the group
.IR group ,
instead of the effective group ID of the calling process.  Either a group name
or a numeric group ID are accepted.
.TP
.BI \-m mode
Install all directories with the file mode bits
.IR mode .
Installs optional
.BR fifo (7)
and
.I down_file 
with
.I mode
.I \-x.
(Default: 2775/0664)
.SH "EXIT STATUS"
The
.B mkfsqueue
program exits 0 for success, 100 for bad usage, and 111 for expected error
cases.  All other exit statuses imply that something beyond the imagination of
the programmer has occured.
.SH EXAMPLES
.BR mkfsqueue
/var/axm/queue/foo /var/axm/queue/bar /var/axm/queue/baz
.SH AUTHORS
Matthew Story <matt.story@axialmarket.com>
.SH COPYRIGHT
Copyright 2012 AxialMarket, All rights Reserved.
.SH SEE ALSO
.BR mkfifo (1),
.BR trigger\-listen (1),
.BR fsq (7)
