.TH fsq-down 1 "2012-06-12" "AxialMarket" "AxialMarket System Commands Manual"
.SH NAME
fsq\-down \- a program for turning off queues
.BR fsq (7)
.SH SYNOPSIS
.B "fsq down"
.BR "" "[ " flags " ]"
.IR "" " queue " [ " queue " [...]]]"
.br
.B "fsq down"
.BR "" "[ " \-h | \-\-help " ]"
.BR "" "[ " \-v | \-\-verbose " ]"
.BR "" "[ " \-u user| \-\-user=user " ]"
.BR "" "[ " \-g group| \-\-group=group " ]"
.BR "" "[ " \-m mode| \-\-mode=mode " ]"
.IR "" "         " queue " [ " queue " [...]]]"
.SH DESCRIPTION
.BR fsq\-down (1)
uses the
.BR fsq (7)
.B down program
 to turn off queues by adding a file named down.
This stops a queue from being scanned.
.sp
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
.br
Print an extended usage to stdout and exit with exit status
.IR 0 .
Should
.BR fsq\-down (1)
fail due to a bad usage a terse usage will be printed to stderr and
will exit with exit status
.IR "100".
.TP
.BR \-v ", " \-\-verbose
.br
Print additional diagnostic information to
.BR stderr 
.TP
.BR \-u user", " \-\-user=user
.br
create down file owned by this user (username or id).
.TP
.BR \-g group", " \-\-group=group
.br
create down file owned by this group
.TP
.BR \-m mode", " \-\-mode=mode
.br
linux octal permission representation. if a down file already exists, 
fsq-down(1) will chown or chmod the existing file based on these arguments.
.sp
.SH SEE ALSO
.TP
fsq-up(1), fsq(1), chmod(2), chown(2), fsq(7)
