.TH fsq-up 1 "2012-06-12" "Axial" "Axial System Commands Manual"
.SH NAME
fsq\-up \- Enable a queue to be scanned 
.SH SYNOPSIS
.BR
.B "fsq up"
.BR "" "[ " \-h | \-\-help " ]"
.BR "" "[ " \-v | \-\-verbose " ]"
.BR "" queue " [ " queue " [...]]]"
.SH DESCRIPTION
.BR fsq\-up (1)
uses the
.BR fsq (7)
.B up
function to turn on "downed" queues\.  
Downed queues cannot be scanned\.  
Upping a queue allows it to be scanned\.
.sp
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
.br
Print an extended usage to stdout and exit with exit status
.IR 0 .
Should
.BR fsq\-up (1)
fail due to a bad usage, a terse usage will be printed to stderr, and
.BR fsq\-up (1)
will exit with exit status
.IR 100 .
.TP
.BR \-v ", " \-\-verbose
.br
Print additional diagnostic information to
.BR stderr .

